G="node ../../gen-image.mjs"
$G "Wide-angle security camera view from a ceiling corner inside a small neighborhood convenience shop looking toward the glass entrance door, door half open, a brown cardboard parcel resting on the floor by the doorway, one person seen only from the back walking out through the door, shelves at the sides, late afternoon light, muted realistic CCTV color, slight fisheye, sharp, photoreal, no faces, no people facing camera, no text, no letters, no logos, no timestamp overlay" hero.png 16:9 2K > hero.log 2>&1 &
$G "Indoor home security camera view from a high wall corner looking at a wooden front door left ajar, a slice of daylight coming through the gap, entry hallway with a small rug and coat hooks, quiet, photoreal, muted color, no people, no text, no letters, no logos" door.png 3:2 2K > door.log 2>&1 &
$G "Night view from a home doorbell camera: a hooded figure seen from behind and slightly above walking toward a house side gate along a garden path, motion-blur, porch light, dark blue night tones, photoreal, no faces visible, no text, no letters, no logos" intruder.png 3:2 2K > intruder.log 2>&1 &
$G "Straight top-down overhead camera view of a shop entrance floor with five shoppers walking in different directions seen only from directly above (tops of heads and shoulders, no faces), tiled floor, doorway threshold line, daylight, photoreal, no text, no letters, no logos" count.png 3:2 2K > count.log 2>&1 &
$G "Home security camera view from a ceiling corner of a calm bright living room of an older person: armchair, small table with reading glasses, walking cane leaning on the chair, window with soft daylight, rug, photoreal, warm muted color, no people, no text, no letters, no logos" fall.png 3:2 2K > fall.log 2>&1 &
$G "Street pole camera view of a residential sidewalk with a large pile of cut tree branches and pruned garden waste left at the curb next to a parked car, Israeli neighborhood, midday sun, photoreal, no people, no text, no letters, no logos, no license plates readable" pruning.png 3:2 2K > pruning.log 2>&1 &
$G "Street-level camera view of a broken city sidewalk: cracked and uplifted concrete paving tiles pushed up by a tree root, small hazard, urban residential street, overcast daylight, photoreal, no people, no text, no letters, no logos" sidewalk.png 3:2 2K > sidewalk.log 2>&1 &
wait
echo ALLDONE
